panel:
  - name: "Hello"
    topic: "/example"
    topic_type: "std_msgs/msg/String"
    message:
      data: "Hello, world!"
  - name: "Forward"
    topic: "/cmd_vel"
    topic_type: "geometry_msgs/msg/Twist"
    message:
      linear:
        x: 0.5
    qos:
      reliability: "reliable"
      durability: "transient_local"
      history: "keep_all"
  - name: "Move"
    topic: "/cmd_vel"
    topic_type: "geometry_msgs/msg/Twist"
    message:
      linear:
        x: 0.5
        y: 0.0
      angular:
        z: 0.5
    qos:
      reliability: "best_effort"
      durability: "volatile"
      history: "keep_last"
      depth: 10
      
